### ISSUE TITLE
Remove duplicates in all types

### ISSUE THREAD

**Issue by fran2810** [dana-team/platform-backend#63]
In many of our types we have code duplication for example the createCapp and the updateCapp all have (annotations, labels and spec)

https://github.com/dana-team/platform-backend/blob/108d9bb7e14b5a0a180830cd05947d8316553bd0/src/types/capp.go#L15-L30

**Comment by mzeevi** [comment]
Types cannot be embedded in other types in a useful way here, so closing the issue
